version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: supervision_iot
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    # si quieres volcar config personalizada:
    # volumes:
    #   - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  app:
    build: .
    depends_on:
      - db
      - mosquitto
    environment:
      # variables que use tu database.py
      DATABASE_URL: postgresql://user:user@db:5432/supervision_iot
      MQTT_BROKER_HOST: mosquitto
      MQTT_BROKER_PORT: "1883"
    ports:
      - "8000:8000"
    volumes:
      - .:/app      # para hot-reload

volumes:
  db_data:
